// This file is going to store all of the strings that will be used throughout the app
export default {
    OfTheDay: 'Of the Day',
    LetsGo: 'Let\'s go',
    ExploreTopicsYouLove: 'Explore\nTopics you love',
    SubscribeToYourFavorites: 'Subscribe\nTo your favorites',
    GetDailyMessages: 'Get\nDaily messages',
    Next: 'Next',
    Go: 'Go',
    Skip: 'Skip',
    Explore: 'Explore',
    Profile: 'My Profile',
    SearchMyTopics: 'Search my topics...',
    OTDManager: 'OTD\nManager',
    SearchAllTopics: 'Search all topics...',
    SignUp: 'Sign Up',
    EmailDotDotDot: 'Email...',
    PhoneNumberDotDotDot: 'Phone Number...',
    PasswordDotDotDot: 'Password...',
    IHaveReadAndAcceptedThe: 'I have read and accept the ',
    TermsAndConditions: 'Terms & Conditions',
    Create: 'Create',
    AlreadyHaveAnAccount: 'Already have an account? ',
    LogIn: 'Log In',
    Whoops: 'Whoops',
    Ok: 'Ok',
    PleaseEnterAValidEmailAddress: 'Please enter a valid email address.',
    PleaseEnterAValidPhoneNumber: 'Please enter a valid phone number.',
    PleaseEnterAValidPassword: 'Your password must be greater than 6 characters.',
    PleaseAcceptTheTermsAndConditions: 'Please accept the terms and conditions.',
    ThisEmailIsInUse: 'This email is already in use. Please go back and log in.',
    SaveInfo: 'Save Info',
    MyAccount: 'My\nAccount',
    PrivacyPolicy: 'Privacy Policy',
    SignOut: 'Sign Out',
    WelcomeBack: 'Welcome Back',
    ForgotPasswordQuestion: 'Forgot Password?',
    IncorretInfo: 'Incorrect Info',
    IncorrectEmailPassword: 'Your email or password is incorrect. Please try again.',
    Success: 'Success',
    YourInfoHasBeenSaved: 'Your info has been saved.',
    YourPasswordIsIncorrect: 'Your password is incorrect',
    ForgotPassword: 'Forgot Password',
    ItHappens: 'It happens!',
    SendResetEmail: 'Send Reset Email',
    EmailSent: 'Email Sent',
    EmailSentMessage: 'We\'ve sent you an email to reset your password. Please check your spam folders.',
    CreateYourFirstTopic: 'Create\nYour first topic',
    ShareYourMessagesWithTheWorld: 'Share your\nMessages with the world',
    TopicNameDotDotDot: 'Topic name...',
    TopicSubname: 'Topic Subname...',
    TopicDescription: 'Topic description...',
    Following: 'Following',
    CreateTopic: 'Create Topic',
    AddTag: 'Add tag',
    PleaseEnterTopicInfo: 'Please enter a topic name & description.',
    PleaseEnterTopicImages: 'Please upload images for your topic.',
    CreateNewTopic: 'Create\nNew Topic',
    Follower: 'Follower',
    Followers: 'Followers',
    SendYourTopicAMessage: 'Send your topic a message...',
    LoadEarlier: 'Load Earlier',
    Save: 'Save',
    JoinATopic: 'Join a Topic',
    TopTrendingTopics: 'Top trending topics',
    OurTopTopicsForYou: 'Our top topics for you'

}