// This file is going to store all of the strings that will be used throughout the app
export default {
    Topics: 'Topics',
    LetsGo: 'Let\'s go',
    ExploreTopicsYouLove: 'Explore\nTopics you love',
    SubscribeToYourFavorites: 'Subscribe\nTo your favorites',
    StartYourOwn: 'Start\nYour own',
    Next: 'Next',
    Go: 'Go',
    Skip: 'Skip',
    MyTopics: 'My Topics',
    Explore: 'Explore',
    Profile: 'My Profile',
    SearchMyTopics: 'Search my topics...',
    TopicsManager: 'Topics\nManager',
    SearchAllTopics: 'Search all topics...',
    WelcomeToTopics: 'Welcome to\nTopics!',
    EmailDotDotDot: 'Email...',
    PhoneNumberDotDotDot: 'Phone Number...',
    PasswordDotDotDot: 'Password...',
    IHaveReadAndAcceptedThe: 'I have read and accept the ',
    TermsAndConditions: 'Terms & Conditions',
    Create: 'Create',
    AlreadyHaveAnAccount: 'Already have an account? ',
    LogIn: 'Log in',
    Whoops: 'Whoops',
    Ok: 'Ok',
    PleaseEnterAValidEmailAddress: 'Please enter a valid email address.',
    PleaseEnterAValidPhoneNumber: 'Please enter a valid phone number.',
    PleaseEnterAValidPassword: 'Your password must be greater than 6 characters.',
    PleaseAcceptTheTermsAndConditions: 'Please accept the terms and conditions.',
    ThisEmailIsInUse: 'This email is already in use. Please go back and log in.',
    SaveInfo: 'Save Info',
    MyAccount: 'My\nAccount',
    PrivacyPolicy: 'Privacy Policy',
    SignOut: 'Sign Out'

}